security:
    
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]
    
    providers:
        user_manage:
            entity:
                class: App\Entity\User
                property: username
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  
     
        admin_panel:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
                username_parameter: login[username]
                password_parameter: login[password]
               
            logout:
                path: logout
                target: home
                
            remember_me:
                secret:   42664c6559670934986471b6b082032d
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain: ~
                remember_me_parameter: login[remember_me]
                
           
    access_control:
       # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER} 

        

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
